CREATE TABLE Account (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	RoleId UNIQUEIDENTIFIER REFERENCES [Role] (Id) NOT NULL,
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	PasswordHash NVARCHAR(50) NOT NULL
)