CREATE TABLE ProductImage (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	ProductId UNIQUEIDENTIFIER NOT NULL,
	Url NVARCHAR(2083) NOT NULL,
	CONSTRAINT FK_ProductId FOREIGN KEY (ProductId) REFERENCES Product (Id) ON DELETE CASCADE
);