CREATE TABLE Product (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	CategoryId UNIQUEIDENTIFIER REFERENCES ProductCategory (Id) NOT NULL,
	Name VARCHAR(30) NOT NULL,
	Description NVARCHAR(1000),
	Price MONEY
);