CREATE TABLE GROUPS
(
    ID     NUMBER PRIMARY KEY NOT NULL,
    NAME   VARCHAR2(50) NOT NULL,
    C_VAL  NUMBER
);

CREATE TABLE STUDENTS
(
    ID        NUMBER PRIMARY KEY,
    NAME      VARCHAR2(50),
    GROUP_ID  NUMBER REFERENCES GROUPS(id)
); 
