MODEL_USER_ID = 000000
MODEL_USER_NAME = 'test_user'
MODEL_USER_PASSWORD = 'test_password'

MODEL_CITY_NAME = 'test_city'

TELEGRAM_USER_ID = 111111
TELEGRAM_USER_NAME = 'telegram_test_user'

CHAT_ID = 0

MESSAGE_ID = 222222
